steps:
- name: node:10.15.1
  entrypoint: npm
  args: ['install']
  dir: app
- name: node:10.15.1
  entrypoint: npm
  args: ['run', 'build']
  dir: app
- name: ubuntu:18.04
  args: ['ls', '-lR', 'dist']
  dir: app
