steps:
- name: node:20
  entrypoint: npm
  args: ['install']
  dir: app
- name: node:20
  entrypoint: npm
  args: ['install']
  dir: main
- name: node:20
  entrypoint: npm
  args: ['run', 'build']
  dir: app
- name: gcr.io/cloud-builders/gsutil
  args: ['-m', 'cp', '-r', '.', 'gs://leftoverbytes-content']
  dir: app/dist
- name: gcr.io/cloud-builders/gcloud
  args: ['datastore', 'indexes', 'create', 'index.yaml']
  dir: main
- name: gcr.io/cloud-builders/gcloud
  args: ['app', 'deploy', '--no-promote']
  dir: main
