runtime: nodejs10
handlers:
- url: /ads\.txt
  upload: ads\.txt
  static_files: ads.txt
- url: /robots\.txt
  upload: robots\.txt
  static_files: robots.txt
- url: /manifest\.json
  upload: manifest\.json
  static_files: manifest.json
- url: /service-worker\.js
  upload: service-worker\.js
  static_files: service-worker.js
- url: /.*
  secure: always
  redirect_http_response_code: 301
  script: auto
env_variables:
  STORAGE_BUCKET: leftoverbytes.appspot.com
indexes:
- kind: Comment
  properties:
  - name: post
  - name: created
