runtime: nodejs10
handlers:
- url: /ads\.txt
  upload: ads\.txt
  static_files: ads.txt
- url: /robots\.txt
  upload: robots\.txt
  static_files: robots.txt
- url: /manifest\.json
  upload: manifest\.json
  static_files: manifest.json
- url: /service-worker\.js
  upload: service-worker\.js
  static_files: service-worker.js
- url: /.*
  secure: always
  redirect_http_response_code: 301
  script: auto
env_variables:
  CONTENTS: https://storage.googleapis.com/leftoverbytes-content
  CHART_SOURCE: https://gitlab.com/leftoverbytes/helm-charts
  STORAGE_BUCKET: leftoverbytes.appspot.com
  GOOGLE_LOGIN_URL: https://accounts.google.com/o/oauth2/v2/auth
  GOOGLE_TOKEN_URL: https://oauth2.googleapis.com/token
  FACEBOOK_LOGIN_URL: https://www.facebook.com/v5.0/dialog/oauth
  FACEBOOK_TOKEN_URL: https://graph.facebook.com/v5.0/oauth/access_token
  FACEBOOK_INFO_URL: https://graph.facebook.com/me
  GITHUB_LOGIN_URL: https://github.com/login/oauth/authorize
  GITHUB_TOKEN_URL: https://github.com/login/oauth/access_token
  GITHUB_INFO_URL: https://api.github.com/user
  NOTIFY_RECIPIENT: Ryan Calhoun <ryan@leftoverbytes.com>
  NOTIFY_SENDER: Leftover Bytes <notify@leftoverbytes.com>
